title: Learning Notes
description: Ghi chú học tập cá nhân
encoding: utf-8
lang: vi

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

search_enabled: true
nav_sort: case_insensitive

markdown: kramdown
kramdown:
  input: GFM

permalink: /:categories/:slug/

collections:
  posts:
    output: true
    permalink: /:categories/:slug/

just_the_docs:
  collections:
    posts:
      name: Notes
      nav_fold: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: default
