title: Learning Notes
description: Ghi chú học tập cá nhân
theme: minima
encoding: utf-8
lang: vi

markdown: kramdown
kramdown:
  input: GFM

permalink: /:categories/:slug/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
